### ISSUE TITLE
Push notification support

### ISSUE THREAD

**Issue by owais** [martinrusev/imbox#1]
Interesting! We really need something like requests for IMAP. Is support for Push notifications planned?

**Comment by wagner-certat** [comment]
Is this implemented?

**Comment by martinrusev** [comment]
@wagner-certat IDLE is not part of the IMAP4 library used in Imbox (https://docs.python.org/3.5/library/imaplib.html). Implementing this feature will required third party libraries which complicates the project quite a bit. If IDLE becomes part of IMAP4, I will implement it right away

**Comment by wagner-certat** [comment]
Ah, thanks for the explanation!
