### ISSUE TITLE
Display an explicit method to run the tests

### ISSUE THREAD

**Issue by sblondon** [martinrusev/imbox#101]
When I write a patch to imbox library, I run the tests with ```tox``` and a tox.ini file containing:
```
[tox]
envlist = py34,py35 # should add others versions
[testenv]
deps=nose
commands=nosetests
```

Perhaps you have a better way to run the tests?
I think it would be good to document it in a paragraph at the end of the README file (and including the tox file or whatever file required).

I can do a PR if you want.

**Comment by martinrusev** [comment]
@sblondon A good way to run the tests (at least on ubuntu) will be:

```sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.X
```
and it tox.ini

```
[tox]
envlist = py32,py33,py34,py35,py36
[testenv]
deps=nose
commands=nosetests -v
```
Also I think 3.2 can be deprecated at this point, because it was EOL last year (https://www.python.org/dev/peps/pep-0392/#lifespan)

**Comment by wagner-certat** [comment]
3.3 had it's EOL in September.

You can run the tests also without tox using `python3 setup.py test`.
