### ISSUE TITLE
Is imbox Python 3-only now?

### ISSUE THREAD

**Issue by dsuch** [martinrusev/imbox#103]
Hello,

I'm using imbox 0.6 with Python 2.7 and I have just spotted that imbox 0.9 specifies requirements as 'Python (3.3, 3.4, 3.5, 3.6)'.

Does that mean that imbox is Python 3-only now? If so, can you tell me what the latest version to support Python 2.7 was?

Thanks.

**Comment by martinrusev** [comment]
Hi @dsuch,

The latest release with support for Python 2.7 was 0.8.5

**Comment by dsuch** [comment]
I see, thanks for the update @martinrusev.
