### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'starttls' (Imbox class)

### ISSUE THREAD

**Issue by Pawamoy** [martinrusev/imbox#110]
Version: 0.9.
Imbox class `__init__` method help text:
> `__init__(self, hostname, username=None, password=None, ssl=True, port=None, ssl_context=None, policy=None)`

**Comment by wagner-certat** [comment]
Starttls support has been added after 0.9

**Comment by martinrusev** [comment]
@Pawamoy Will push the latest to pypi, sorry about the confusion

**Comment by Pawamoy** [comment]
I think this has been fixed (just tried with Imbox 0.9.5 and didn't get the error). Thanks!
