### ISSUE TITLE
Exception raised by the logging if there is an encoding problem in sender name

### ISSUE THREAD

**Issue by sblondon** [martinrusev/imbox#116]
In imbox/parser.py, the decoding of the name and e-mail address is done by ```decode_mail_header()```. It's done 3 times, by ```imbox.utils.str_encode()``` function:
 * line 36: ```logger.debug()``` formats the name of the sender. ```errors``` parameter is not set at the call so it's in strict mode.
 * lines 38 and 42, in order to set ```headers[index]```: Encoding problems are fixed by the ```replace``` value to third parameter of the ```str_decode()``` call ().

I have a case where it's a problem: the content of the name is not correct utf-8 string so I get an ```UnicodeDecodeError``` due to the logger and not the functional code of the library. If I set ```errors='replace'``` for the ```str_encode()``` call of the logger, it works properly.

In my opinion, setting errors parameter to ```replace``` is a good way to fix it. What do you think about it?
I can do a PR with my testcase for unit testing it.

**Comment by martinrusev** [comment]
@sblondon Sounds like a good solution. I will merge the PR whenever you are ready

**Comment by sblondon** [comment]
I close the issue because the PR is merged.
