### ISSUE TITLE
encapsulate the generator returned by Imbox.messages()

### ISSUE THREAD

**Issue by zevaverbach** [martinrusev/imbox#121]
This would allow the implementation of a `__len__` method on such an encapsulating object -- so that the calling code can check how many messages match a particular search -- as well as a "refreshing" or priming of the encapsulated generator when iteration is attempted after `StopIteration` is raised.  Also, the `__repr__` of such an object could be more informative than the current `<generator object Imbox.fetch_list at 0x000000`.

@martinrusev Would you accept a PR with such changes?

**Comment by martinrusev** [comment]
@zevaverbach A PR would be more than welcome.
