### ISSUE TITLE
support Gmail's IMAP extensions

### ISSUE THREAD

**Issue by zevaverbach** [martinrusev/imbox#123]
[As seen here](https://developers.google.com/gmail/imap/imap-extensions).  Happy to implement that for you if you think you'd be open to such a PR.

**Comment by martinrusev** [comment]
@zevaverbach I understand the benefit of adding those IMAP extensions. I have some concerns about making imbox vendor specific. If I had to support them, maybe putting the gmail specific parts into a  `vendors` folder and calling it with  `from imbox.vendors import gmail` could be an option

**Comment by zevaverbach** [comment]
@martinrusev understood.  You'd prefer that to 

- having a keyword argument in `build_search_query` called `hostname`, then 
- checking for a value of `imap.gmail.com` when unpacking the other `kwargs`, and
- for example, if `label` is in `kwargs`, append `(X-GM-LABELS <label>)` to `query`?
