### ISSUE TITLE
parse flags 

### ISSUE THREAD

**Issue by zevaverbach** [martinrusev/imbox#126]
Parse flags in `parse_email` and add them as a list `parsed_email.flags`.  Would you accept such a PR?

**Comment by zevaverbach** [comment]
this could be implemented using `imaplib.ParseFlags`.

**Comment by zevaverbach** [comment]
possibly this would also help resolve #22.

**Comment by martinrusev** [comment]
@zevaverbach This would be a very helpful addition

**Comment by pycebs** [comment]
@zevaverbach Will this be pushed to PyPI anytime soon?

**Comment by zevaverbach** [comment]
@pycebs I'm not a maintainer of the project, so you'll have to ask @martinrusev.  However, you could `pip install pip install git+https://github.com/martinrusev/imbox/` while you wait for that.

**Comment by martinrusev** [comment]
@pycebs Just pushed to PyPI, all the recent changes are wrapped in the 0.9.6 release
