### ISSUE TITLE
change documentation to reflect that Imbox.messages() gets all messages in the inbox

### ISSUE THREAD

**Issue by zevaverbach** [martinrusev/imbox#128]
The comment and var name in the docs strongly imply `all_messages`, but `Imbox.messages()` only returns a small subset of messages, whichever ones are in the inbox, not archived.  Would you accept such a PR?

**Comment by zevaverbach** [comment]
It might be good to also change the logging in `Imbox.messages` in this case to "Fetch list of messages from inbox." or something similar.

**Comment by martinrusev** [comment]
@zevaverbach Some verbosity in the logging and docs could be a good addition.
