### ISSUE TITLE
move all code out of __init__.py and into a separate module

### ISSUE THREAD

**Issue by zevaverbach** [martinrusev/imbox#130]
To follow "the principle of least surprise," as most `__init__.py`s are empty or only have imports or `__all__`, and thus that's the expectation.  Would you accept a PR implementing this?

**Comment by martinrusev** [comment]
@zevaverbach Makes sense. A separate module plus the imports put in a  `__all__` list, similar to https://github.com/pallets/jinja/blob/master/jinja2/__init__.py
