### ISSUE TITLE
create vendors module to support idiosyncratic IMAP providers

### ISSUE THREAD

**Issue by zevaverbach** [martinrusev/imbox#131]
This was alluded to in #123.  Here are a few things such a module could support:

- map flag names to standardized `folder` names, and vice versa.  For example, in Gmail the archived messages correspond with `"[Gmail]/All Mail"` (including the double quotes!), whereas in Yahoo Mail it's `Archive`
- when there's an authentication error when instantiating `Imbox`, helpful error messages might be displayed.  For example, with Yahoo: `Have you clicked "Allow apps that use less secure sign in" here?: https://login.yahoo.com/account/security`.
- support IMAP extensions, which at least [Gmail](https://developers.google.com/gmail/imap/imap-extensions) uses. (also alluded to in #123)

Would you accept a PR that accomplishes this, at least for a few large IMAP providers?

**Comment by martinrusev** [comment]
@zevaverbach a vendors module would be an awesome addition. I would gladly accept a PR.

**Comment by zevaverbach** [comment]
Will do! Would it be acceptable to employee such a module “magically“ in the constructor of Imbox?  In addition to being able to do so manually .

**Comment by martinrusev** [comment]
@zevaverbach What I think would work well:

```
# vendors/gmail
GmailMessages(Messages):
   ..... gmail specific logic

# vendors/__init__.py
__all__ = [GmailMessages]

with Imbox('imap.gmail.com',
        username='username',
        password='password', 
vendor="gmail"):
```
   
https://github.com/martinrusev/imbox/blob/master/imbox/__init__.py#L68
```
from imbox.vendors import GmailMessages

# Set the default
messages_class = Messages
if vendor == "gmail":
  messages_class = GmailMessages

return messages_class(connection=self.connection,
                        parser_policy=self.parser_policy,
                        **kwargs)
```

**Comment by zevaverbach** [comment]
@martinrusev super elegant, thank you.  Will submit a PR soon.

**Comment by zevaverbach** [comment]
@martinrusev on second thought, this architecture precludes the first two bullet points in the OP ⬆ because it happens after authentication and folder selection.

Here are two ideas for how to fix this:

1. Would you be open to making it `ImboxGmail` instead?  One justification for this is that `Imbox.copy` and `Imbox.move` will likely need the folder to flag mapping alluded to above, in order to abstract away goofy folder names like `"[Gmail]/Sent Mail"`.
1. implement #133 so such a mapping could live in `Messages` subclasses.  The custom authentication error messages could still be implemented as a dictionary lookup in the `Imbox` constructor when the `self.connection` assignment raises an error.

One of the above, plus per
