### ISSUE TITLE
make Imbox.delete work

### ISSUE THREAD

**Issue by zevaverbach** [martinrusev/imbox#138]
Currently there's a bug, in that it only calls `connection.expunge` and doesn't do `connection.uid('DELETE')`.

**Comment by zevaverbach** [comment]
yikes, apologies!

Zev Averbach
Averbach Transcription
(802) 276-5934
avtranscription.com <http://www.avtranscription.com/>

**Comment by aurelg** [comment]
This bug seems to have been reintroduced, see: https://github.com/martinrusev/imbox/blob/402d66579922ba9717e95bc67535a9fdfe2696bd/imbox/imbox.py#L65-L68

**Comment by sblondon** [comment]
@aurelg you're right, the flag is not set.

I'm not sure the maintainer has been notified because the bug report is closed.
@martinrusev did you see it ?

**Comment by chwba** [comment]
yeah, i just ran into that as well. im using the version that is pushed to pip so i guess ill switch to the repos one now ^^

**Comment by Ri773r** [comment]
the bug is still here
@martinrusev
