### ISSUE TITLE
Email retrieval is very slow

### ISSUE THREAD

**Issue by pycebs** [martinrusev/imbox#150]
I was just playing around with imbox and for me the retreival of emails is very slow.

This is my code:

```
def list_messages(self, folder=None):
        all_inbox_messages = self.account.messages(folder=folder)
        messages = []
        number = 0
        for element in all_inbox_messages:
            number += 1
            print(number)
```
It loads a total of 21 emails and takes about 18 seconds. 

Why is it so slow? My internet speed is fine, I tried it from my desktop and if I try it with Thunderbird or with Geary, my Mailbox loads within 1-2 seconds.

EDIT: I fixed it by using a Pool.

**Comment by n3storm** [comment]
@pycebs care to explain? did you use python3 async features?

thanks in advance
