### ISSUE TITLE
Body.html strange characters "\r\n"

### ISSUE THREAD

**Issue by MattiaFailla** [martinrusev/imbox#171]
![ghhhh](https://user-images.githubusercontent.com/11872425/62905216-cbcdf900-bd69-11e9-9ac5-d22005ec8acc.png)

I'm displaying the result of body['html'] in an html page. What can I do to delete all those "new line" characters from the body of the mail? is it a bug? 

I'm currently fetching mails from an outlook account.

**Comment by MattiaFailla** [comment]
Update: the easiest way to delete those character is via a .replace()
The following characters may appear in you body:
- \t
- \n\r
- \n
- \r
- ['\r\n

Example code:
`body = body.replace(r"['\r\n", "&#13;")`

I'll let this issue open in case of further requests.

**Comment by wagner-certat** [comment]
Are you sure that you display the body correctly? The `[` at the beginning looks like you are representing a list.

**Comment by MattiaFailla** [comment]
Yes, the `[` is due to javascript (I'm sending the body from python to javascript via websocket, in order to simulate a callback to the database). 

Other characters may appear randomly on emails body (also by printing the body on the terminal). I think is a problem with the formatting of the original mail but I'm not sure tho.

**Comment by MattiaFailla** [comment]
Solved by accessing the mail object list.
