### ISSUE TITLE
parse_attachment function line 129 indented less?

### ISSUE THREAD

**Issue by Ri773r** [martinrusev/imbox#188]
https://github.com/martinrusev/imbox/blob/085da0738ec7adc87cc3ee9b4a827ba71a9c9182/imbox/parser.py#L108-L130

attachment ['filename '] is assigned on lines 110 and 129, but line 129 will override the previous value anyway, Is this a bug?

**Comment by wagner-certat** [comment]
That was introduced in #186 which fixed the filename parsing - that's where the overwriting code comes from. I agree that the first statement can be removed.

**Comment by pka69** [comment]
I have this problem. Attachment content-type ix excel file, but filename=''.

**Comment by martinrusev** [comment]
@Ri773r Fixed in https://github.com/martinrusev/imbox/commit/5aabe0dc5d217de34298cffb85f68b4545c1e16f

**Comment by wagner-certat** [comment]
> I have this problem. Attachment content-type is excel file, but filename=''.


Are you sure that this is related?

**Comment by pka69** [comment]
I thought so. 
But now I see it can be something different.
