### ISSUE TITLE
Use TLS to secure the connection

### ISSUE THREAD

**Issue by InsomniakD** [martinrusev/imbox#209]
hello, i can't find any way to make TLS work with imbox is it possible to include an example in the readme.txt ?
Thanks.

**Comment by sebix** [comment]
The example in the readme already contains `ssl=True`

**Comment by InsomniakD** [comment]
Yeah I know for SSL but I talk about TLS because SSL is a bit out of date
When I type startTls=true I think some options are missing and I don't know them. Then if you now how to make it work it would be cool.

**Comment by sebix** [comment]
The starttls parameter is for STARTTLS, not for SSL/TLS.
If you want to ensure that a specific SSL/TLS version is (not) used, you can create a [custom ssl context](https://docs.python.org/3/library/ssl.html#ssl-contexts) (specifically the options `minimum_version`) and pass it as parameter `ssl_context`.

**Comment by InsomniakD** [comment]
oh okay thank you i will dig out in that way tho
