### ISSUE TITLE
How does one tell if an email is read/unread?

### ISSUE THREAD

**Issue by agaskins** [martinrusev/imbox#22]
I see the function to mark items as read... but how do you tell if a message is read or unread already? For example, say I'm going to list all the emails in the inbox, and I need to somehow flag read items with a different background color or something... A pretty basic requirement. However, I don't see this information in the output from messages() or any other fetch_\* method. Am I missing something?

**Comment by OmarIbannez** [comment]
Hi, Did you figure out how to do this? I need this same functionality

**Comment by ryo96** [comment]
`unread_messages = imbox.messages(unread=True)` do this to filter unread messages

**Comment by agaskins** [comment]
I guess what I wanted was a way to get all messages and then as I iterate thru them be able to tell which are read or unread. It's been a few years but I actually have a new project that requires IMAP support so I'm thinking about giving imbox another go. Is there a way to add a key for read/unread status to the message objects when I retrieve them, for example? Like the examples on the project page here, but with read/unread status in there. I'm not a python wizard, so maybe this is trivial and I'm just not seeing it. I guess fetching read and unread in two separate queries would work (which I think is what the solution above implies for my case) but that would seem cumbersome with less straight forward fetches.

**Comment by zevaverbach** [comment]
@agaskins now that #126 is implemented (parsing flags), every message has a `flags` attribute.  Using Gmail to manually test your use case, I find that if `b'\\Seen'` is in that `flags` list, then the message is unread; if not, it's unread.

**Comment by agaskins** [comment]
Wow, what serendipity! I was just going thru my perpetually unfinished projects folder and thought this project was worth revisiting again. This is all the more motivation. I'm glad to hear this feature was implemented, and thank you for the follow up @zevaverbach !
