### ISSUE TITLE
Marking e-mails as not seen

### ISSUE THREAD

**Issue by PWrzesinski** [martinrusev/imbox#241]
I think it would be useful to have a method for marking e-mails as not seen, so reversing the `mark_seen` method. I do need it in my project. Would it be something as simple as adding:

    def mark_unseen(self, uid):
        logger.info("Delete \\Seen FLAG from UID {}".format(int(uid)))
        self.connection.uid('STORE', uid, '-FLAGS', '(\\Seen)')

inside Imbox.py? If so I'd be happy to make a PR.

**Comment by codingbeast** [comment]
imbox.mark_seen(uid)

**Comment by PWrzesinski** [comment]
> imbox.mark_seen(uid)

Thanks, but please read the question again. I want the opposite.
