### ISSUE TITLE
Is there a way to get gmail drafts?

### ISSUE THREAD

**Issue by zhao-ji** [martinrusev/imbox#39]
Now there are some drafts in my Gmail, I want to export it, but I found there are no way to do.

**Comment by martinrusev** [comment]
How about something like this:

    messages_folder = imbox.messages(folder='[Gmail]/Drafts')

**Comment by zhao-ji** [comment]
Does not work.
I put some drafts in a folder which create by myself, and I can get the mails in that folder, but there is no draft in it.

**Comment by martinrusev** [comment]
Can you take a look at your Gmail settings and see if this option is checked: 

![drafts](https://cloud.githubusercontent.com/assets/103003/5737964/9c36a296-9bef-11e4-8929-403f160c6838.png)

**Comment by zhao-ji** [comment]
All options is checked.
Anyone can get the drafts?
If so I should check my code...sorry
