### ISSUE TITLE
Push new release to pypi

### ISSUE THREAD

**Issue by wkiser** [martinrusev/imbox#54]
Any chance you could push a new release to pypi? It would be helpful to have some of the new features. Specifically cc/bcc parsing.

Thanks!

**Comment by frennkie** [comment]
+1

I also ran into a python 3 encoding related issue with the pypi version which is already fixed in master.
Please release an update of imbox to pypi.

Thanks
frennkie

**Comment by martinrusev** [comment]
@frennkie Done
