### ISSUE TITLE
Auth failure: Google prevents sign-in attempt

### ISSUE THREAD

**Issue by ProbonoBonobo** [martinrusev/imbox#60]
I disabled two-factor authentication, but that wasn't sufficient to authenticate the IMAP connection. Here's the email I received from Google:

>Hi Kevin,
>Someone just tried to sign in to your Google Account [REDACTED] from an app that doesn't meet modern security standards.

>We strongly recommend that you use a secure app, like Gmail, to access your account. All apps made by Google meet these security standards. Using a less secure app, on the other hand, could leave your account vulnerable. Learn more.

>[...]

>Best,
>The Google Accounts team

There doesn't seem to be a way to grant access – the failure appears to be terminal. As a temporary workaround, is it possible to bypass the authentication step entirely and use imbox on a local .mbox file?

**Comment by martinrusev** [comment]
Hi @ProbonoBonobo,

I found this: https://support.google.com/accounts/answer/6010255
