### ISSUE TITLE
got an unexpected keyword argument 'ssl_context'

### ISSUE THREAD

**Issue by boussouira** [martinrusev/imbox#70]
Please note that:
[`ssl_context = pythonssllib.create_default_context()`](https://github.com/martinrusev/imbox/blob/64c06c1915acad0da7f037959a0d0c0464f1cf2f/imbox/imap.py#L21)
is new in python version 2.7.9.

after installing 2.7.11, i get this error:

```
>>> imbox = Imbox('imap.gmail.com', username='...@gmail.com', password='...')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/naruto/Programming/imap_test/venv/lib/python2.7/site-packages/imbox/__init__.py", line 15, in __init__
    ssl_context=None)
  File "/home/naruto/Programming/imap_test/venv/lib/python2.7/site-packages/imbox/imap.py", line 28, in __init__
    self.server = self.transport(self.hostname, self.port, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'ssl_context'
```

looks like `ssl_context` argument is not supported in 2.7

**Comment by icam0** [comment]
How do you resolve this issue? When I turn-off ssl completely the package just freezes

**Comment by boussouira** [comment]
I didn't resolve it, probably I'll use an other library.

**Comment by sebix** [comment]
> I didn't resolve it, probably I'll use an other library.

Or make the step forward to Python 3.

**Comment by sebix** [comment]
Python 2.7 does not allow specifying `ssl_context`, thus no certificates can be validated. I want to encourage you to *not* disable this and use Python 3 only. I consider Python 2.7 a security risk.

**Comment by martinrusev** [comment]
What about this line here: https://docs.python.org/2/library/ssl.html#ssl.create_default_context

**Comment by sebix** [comment]
@martinrusev The point is, that there's no `ssl_context` parameter for [`imaplib.IMAP4_SSL`](https://docs.python.org/2.7/library/imaplib.html?highlight=imap4#imaplib.IMAP4_SSL)

**Comment by bhtucker** [comment]
This is a definite issue — the project should probably just come out and say it doesn't support Python 2.7.

**Comment by martinrusev** [comment]
Done: https://github.com/martinrusev/imbox/blob/master/README.md#requirements

**Comment by sebix** [comment]
Also change it in setup.py: https://github.com/martinrusev/imbox/blob/master/setup.py#L26
