### ISSUE TITLE
UTF-8/UnicecodeDecodeError

### ISSUE THREAD

**Issue by nulfox** [martinrusev/imbox#83]
Name: imbox
Version: 0.8.5

Seeing decoding exceptions on certain messages

'utf-8' codec can't decode byte 0xa9 in position 21957: invalid start byte" type="<class 'UnicodeDecodeError'>
  File "/usr/lib64/python3.4/site-packages/imbox/__init__.py", line 50, in fetch_list
    yield (uid, self.fetch_by_uid(uid))
  File "/usr/lib64/python3.4/site-packages/imbox/__init__.py", line 41, in fetch_by_uid
    email_object = parse_email(raw_email)
  File "/usr/lib64/python3.4/site-packages/imbox/parser.py", line 126, in parse_email
    raw_email = str_encode(raw_email, 'utf-8')
  File "/usr/lib64/python3.4/site-packages/imbox/utils.py", line 10, in str_encode
    return str(value, encoding, errors)""

**Comment by bighelmet7** [comment]
Have any solution for this error? I get this one:
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 1293: invalid continuation byte

**Comment by wagner-certat** [comment]
imbox could ignore such encoding issues by using the `errors='ignore'` parameter for decode. Tough I would prefer that this is the default behavior.

**Comment by mecarus** [comment]
I believe there are some steps that can be taken to avoid the issue. I will take a look at specific e-mail and what is causing it. Ideally, e-mail client shouldn't throw exceptions when processing e-mails - but agree - using ignore would not be a good solution.

**Comment by meganspeir** [comment]
@mecarus did you ever find a solution to this? I am having the same issue.
